### ISSUE TITLE
Support Wayland on Linux

### ISSUE THREAD

**Issue by LunaTheFoxgirl** [BindBC/bindbc-opengl#29]
Currently bindbc-opengl only loads OpenGL symbols from the X11 server, which means applications will crash on Wayland desktops.
Solution is to check the `XDG_SESSION_TYPE` environment variable on Linux to see whether it reports `x11` or `wayland`, if wayland is the active session type. then both libgl and libegl should be loaded, with libegl providing `GetProcAddress` (`eglGetProcAddress`) and `GetCurrentContext` (`eglGetCurrentContext`) and libgl providing all the OpenGL functions.

**Comment by mdparker** [comment]
Thanks. I'll see about getting this done as soon as I can. I think I have a version of Ubuntu that supports Wayland on a laptop. I can test on that.

**Comment by grillo-delmal** [comment]
I don't know if it is of any help, but I made this patch wile debuging the problem, it brings wayland support (by destroying everything else).
I don't want to make a PR since I'm not experienced on the nuances of dlang, but I hope it helps as a reference.
[bindbc-opengl-wayland.patch](https://github.com/BindBC/bindbc-opengl/files/8976066/bindbc-opengl-wayland.patch.txt)
.

**Comment by mdparker** [comment]
@LunaTheFoxgirl @grillo-delmal I've pushed a new "wayland" branch with the changes. I managed to build and run a simple GLFW + OpenGL app on an Ubuntu 22.04 VM running Wayland. So it looks like everything is okay.

Before I tag a release, however, I'd like to ask you guys to checkout the new branch, set your existing bindbc-opengl dependency to use `path=` rather than `version=` (or run `dub add-local` or whatever works for you) and make sure it's working as intended in a real project.

Thanks for reporting this, and thanks in advance for testing it out!

**Comment by grillo-delmal** [comment]
I made a quick check on my computer and noticed that for some reason this comparison is not working.

https://github.com/BindBC/bindbc-opengl/blob/wayland/source/bindbc/opengl/context.d#L82

It might be me, but I'll check again later today when I have time

**Comment by mdparker** [comment]
@grillo-delmal Ah. That's a bug. There should be an `==0` in there. It seems I wasn't running on Wayland after all?

**Comment by mdparker** [comment]
@LunaTheFoxgirl @grillo-delmal Okay. So, here's what's happening for me. The environment is definitely Wayland, and strcmp is definitely returning 0. So what that means for me is that the normal glx code path is taken and everything works. When I fix the strcmp test to work properly, the egl path is taken and it fails because it can't load libEGL.

**Comment by LunaTheFoxgirl** [comment]
Since you're running in a virtual machine, maybe the OpenGL ES drivers are not installed? EGL is a part of GLES, but also used for instantiating desktop GL surfaces

**Comment by mdparker** [comment]
Actually, I was wrong. libEGL is there (I forgot my how my own error handling code works in bindbc.loader and misinterpreted the message I printed). And the functions are loading successfully. So that means the problem is something else.

**Comment by mdparker** [comment]
Okay. It's the call to `getCurrentContext` that's after I point it at the symbol in libEGL. 

It's well past my bedtime now, so I'll have to put off further investigation until tomorrow.

**Comment by grillo-delmal** [comment]
> @grillo-delmal Ah. That's a bug. There should be an `==0` in there. It seems I wasn't running on Wayland after all?

I tested the code with this change and it actually works on my environment 👍

**Comment by mdparker** [comment]
Right. I was a bit silly last night. After a good night's sleep and actually checking the return value of `loadOpenGL`, I was able to find the issue pretty quickly.

Ubuntu 22.04 runs Wayland, but all of the X stuff is still enabled by default. So `apt install libglfw3` gets a version of glfw compiled with X11 support. In that case, `eglGetCurrentContext` will always return null, and we must continue to use the glX stuff instead.

So I fixed things up to account for that and verified that it works using both libglfw3 and libglfw3-wayland.

I've pushed the changes, so if you guys can test it out one more time to verify it's all good, I'll merge it into master and tag a new release.

**Comment by mdparker** [comment]
Well, actually, even if it does work for you, the new code will still bomb in the specific case that we're running under Wayland but no context was created before `loadOpenGL` was called. I'll need to figure out a workaround for that.

**Comment by mdparker** [comment]
> which means applications will crash on Wayland desktops.

@LunaTheFoxgirl Could you be more specific about this? Was it an actual crash, or was it that `loadOpenGL` was failing with something like `GLSupport.badLibrary`?

**Comment by grillo-delmal** [comment]
> > which means applications will crash on Wayland desktops.
> 
> @LunaTheFoxgirl Could you be more specific about this? Was it an actual crash, or was it that `loadOpenGL` was failing with something like `GLSupport.badLibrary`?

In the project, `loadOpenGL` was failing returning `GLSupport.noContext`.

Checked the latest commit (both in my environment and on a ubuntu 22.04 VM) and it worked ok 👍

**Comment by mdparker** [comment]
Thanks, @grillo-delmal. That means I can handle the edge case, too. I'm going to refactor things a bit and make one more push. Then I'll have to ask you to test it one more time.

**Comment by mdparker** [comment]
No, nevermind. I actually don't need to do that. The fact that it wasn't a crash means we're good. So I can go ahead and tag a release.

**Comment by mdparker** [comment]
I've tagged v1.0.1. Thanks for the help with this!
