### ISSUE TITLE
Dynamic version loading

### ISSUE THREAD

**Issue by GrimMaple** [BindBC/bindbc-opengl#37]
It would be cool to support dynamic version change, without having to specify that during build.

**Comment by mdparker** [comment]
That's the whole point of the dynamic loading. The compile-time configuration is just for the maximum version you want to support so that the loader knows what to look for. Then at runtime, you can load whichever version is available up to the max supported and structure your code path accordingly. What would you expect the binding to provide beyond what it does now?

**Comment by GrimMaple** [comment]
I don't seem to understand how to load a specific subset of OpenGL based on code, not the version. Can you provide an example?
What I want is something like that:

```d
loadOpenGL(4, 1); // loads just up to 4.1
```

As far as I understand the current code, it will attempt to load anything based on the actual context created, not on what is requested by the user

**Comment by mdparker** [comment]
I see. So please help me understand the use case. Why would you want to load a version of OpenGL lower than the context you created? Why would you not just create the context version you want?

**Comment by GrimMaple** [comment]
The use case is dlangui, which allows the user to select what version of context to load: [link](https://github.com/buggins/dlangui/blob/master/src/dlangui/platforms/common/platform.d#L1840)
dlangui itself requires version 4.6 I think, so it would be good to specify a lower version to load when requested by the user.

I guess, I could just rely on the context itself... but after a little debugging session on Windows it seems like Windows completely ignores what version of context I ask for, and just creates the most recent one anyway :/

**Comment by mdparker** [comment]
> The use case is dlangui, which allows the user to select what version of context to load: [link](https://github.com/buggins/dlangui/blob/master/src/dlangui/platforms/common/platform.d#L1840)
dlangui itself requires version 4.6 I think, so it would be good to specify a lower version to load when requested by the user.

Okay. So by "requires version 4.6", I assume you mean it configured the binding to support 4.6, but it can potentially support contexts of any modern OpenGL version. That's fine. Adding dynamic version selection isn't going to bring any benefit here, and potentially can cause trouble.

Imagine the situation where you have a 4.6 context, and then you call `loadGL(4, 1)`. Now the dlangui user who has requested  4.1 context actually has a 4.6 context with several unloaded functions. That means there's a mismatch between what `glGetVersion` returns and what is actually loaded. That's not a good situation.

The proper thing for dlangui to do here is to create a context matching the requested version.

> but after a little debugging session on Windows it seems like Windows completely ignores what version of context I ask for, and just creates the most recent one anyway

Then it sounds like something's wrong with your context creation code on Windows, or maybe there's a bug in the driver you're testing on. I haven't created a context directly in a very long time, but when using GLFW or SDL on Windows I always get the context version I requested.

Whatever the issue, the feature you're requesting isn't going to help you. You're actually better off with the higher context version, because then if there *is* a code path in the user code that's based on `glGetVersion`, then there's no chance they'll be calling null function pointers as there would be if you asked the binding to load a lower version.

**Comment by GrimMaple** [comment]
I gave much more consideration to the issue on hand. And, I think, relying on `bindbc-opengl` loading functions based on the context created is the best solution I can provide. Though a reasonable question arises: if my `dub.json` is configured with `"versions": ["GL_33"]`, does this mean that `binbc-opengl` will only load functions up to version 3.3 even if context of version 4.0 is requested? I don't think I understand how this works entirely.

**Comment by mdparker** [comment]
> does this mean that binbc-opengl will only load functions up to version 3.3

Yes. What the version does is configure which symbols are compiled into the binary. That way you aren't going to have a bunch of null pointers sitting around from versions you never intend to use. GL_33 means all core symbols up to 3.3 and none higher. If you want to support 4.0, then you need to specify GL_40.

`loadGL` will return the version it actually loaded. E.g., if you've configured GL_40, but are loading from a 3.3 context, then the function will return `GLSupport.GL33`. See:

https://github.com/BindBC/bindbc-opengl#loading-opengl

**Comment by GrimMaple** [comment]
I was more thinking about a vise-versa scenario, where you specified GL_33 in dub, but loading a 4.0 context -- it means 4.0 functions will never be available to the user :V
Essentially, this forces a choice on me: either I have to specify GL_46 in dlangui's `dub.json`, either I have to propagate the use of GL_XX version on the user. I will have to think about which way is better

**Comment by mdparker** [comment]
IMO, if the user is importing bindbc-opengl directly, then it should be up to the user to specify the OpenGL version. If the user is importing via a public import in a dlangui module, then dlangui should specify GL_46 support to cover all bases.

**Comment by GrimMaple** [comment]
After a lot more thought, I think I'll just specify GL_46 and then depend on the context version. Thank you for your participation :)
