### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by therealbluepandabear** [BindBC/bindbc-opengl#38]
Will this library be updated or is it abandoned? I want to use it for a project though I am concerned that if I do find a bug it won't get fixed due to development stalling.

**Comment by therealbluepandabear** [comment]
BTW your work on D bindings is amazing.

**Comment by mdparker** [comment]
Oh, I see what you mean. A lack of updates in this case is just because there's been nothing to update. There hasn't been a release of OpenGL since 4.6, and this binding supports it. Support for extensions is added on an as-needed basis.

The only time anything needs updating is when someone finds a bug or requests support for extensions. So if you find a bug in the binding, either I or @ichordev will fix it.

**Comment by ichordev** [comment]
OpenGL hasn't been updated from 4.6 in 5 years, it doesn't need regular updates. I will probably work on upgrading a bindbc library that is a bit more out-of-date after I'm satisfied with the big bindbc-sdl update & upgrade, but I will eventually get around to upgrading this one too.
