### ISSUE TITLE
Add KHR_blend_equation_advanced and KHR_blend_equation_advanced_coherent extensions

### ISSUE THREAD

**Issue by LunaTheFoxgirl** [BindBC/bindbc-opengl#45]
These extensions are really useful if you need photoshop style blending modes in your software, the extension is currently missing from bindbc-opengl

**Comment by ichordev** [comment]
Unfortunately I do not have time to add this right now as I’m busy working on other BindBC projects. BindBC-OpenGL needs to be updated to the new BindBC format before I work on it personally any further, which is not a priority for me because these bindings are up-to-date with the latest OpenGL release, and I don’t use this library so I don’t really have any great way of quickly testing it.
If you would like to create a PR for this change you’re welcome to. Blend modes can also be implemented via shaders if necessary, though I can understand that this is a less desirable approach.
